# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_path"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "OOP interface for operations on a POSIX pathname"
categories = ["File paths"]
keywords = ["fortran", "paths", "filename"]
homepage = "https://github.com/urbanjost/M_path.git"

[build]
module-naming = true

[library]
source-dir="src"
[dev-dependencies]
M_framework    = { git = "https://github.com/urbanjost/M_framework.git" }
M_system       = { git = "https://github.com/urbanjost/M_system.git" }
[dependencies]
M_io           = { git = "https://github.com/urbanjost/M_io.git" }
M_system       = { git = "https://github.com/urbanjost/M_system.git" }
M_time         = { git = "https://github.com/urbanjost/M_time.git" }
M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }

[[executable]]
name="path"
source-dir="demo"
main="path.f90"

[[test]]
name="test_suite_M_path"
source-dir="test"
main="test_suite_M_path.f90"
[test.dependencies]
M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
